sudo: false
language: php

cache:
  directories:
  - $HOME/.composer/cache

services:
  - memcache
  - mongodb
  - redis-server

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

env:
  matrix:
  - PREFER_LOWEST="--prefer-lowest --prefer-stable"
  - PREFER_LOWEST=""

before_install:
  - pecl channel-update pecl.php.net
  - composer self-update
  - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then pecl config-set preferred_state stable; echo yes | pecl --soft install apcu; fi;
  - phpenv config-add ./.travis_php.ini

install:
  - travis_retry composer update --no-interaction $PREFER_LOWEST --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - if [[ $TRAVIS_PHP_VERSION < 7.4 ]] ; then composer run-script fix-cs; fi;

after_script:
  - if [[ $TRAVIS_PHP_VERSION = 7.3] && [$PREFER_LOWEST  = "" ]] ; then php vendor/bin/php-coveralls -v; fi;

matrix:
  allow_failures:
    - php: nightly
