language: php

before_script:
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then phpenv config-add .travis.ini; fi"
 
services:
  - memcache
  - mongodb
  - redis-server

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
sudo: false

install: travis_retry composer install --no-interaction --prefer-source

after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
