language: php

services:
  - memcache
  - mongodb
  - redis-server

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  
sudo: false

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]] ; then pecl channel-update pecl.php.net; fi;
  - if [[ $TRAVIS_PHP_VERSION =~ 5.[56] ]] ; then echo yes | pecl install apcu; fi;
  - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then pecl config-set preferred_state beta; echo yes | pecl install apcu-4.0.10; fi;
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-add ./.travis_php.ini; fi;
 
install: 
  - travis_retry composer install --no-interaction --prefer-source
  - if [[ $TRAVIS_PHP_VERSION != '5.3' ]]; then composer require cache/integration-tests; fi;

after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
