language: php

before_script:
  - composer self-update
  - composer --dev install
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then echo 'extension=memcache.so\nextension=mongo.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi"
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' && `php-config --vernum` -lt 50500 ]; then echo 'extension=apc.so\napc.enable_cli=1\n' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi"
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' && `php-config --vernum` -ge 50500 ]; then echo 'extension=apcu.so\napc.enable_cli=1\n' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; `pecl install apcu`; fi"
 
services:
  - memcache
  - mongodb
  - redis-server

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm
  
after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
