language: php

services:
  - memcache
  - mongodb
  - redis-server

php:
  - 5.6
  - 7
  - 7.1
  - 7.2

sudo: false

before_install:
  - pecl channel-update pecl.php.net
  - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then pecl config-set preferred_state stable; echo yes | pecl --soft install apcu; fi;
  - phpenv config-add ./.travis_php.ini

install:
  - travis_retry composer install --no-interaction --prefer-source

after_script:
  - php vendor/bin/coveralls -v
