language: php

before_script:
  - composer self-update
  - composer --dev install
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then echo 'apc.enable_cli=1\nextension=memcache.so\nextension=mongo.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi"
  - sh -c "if [ $TRAVIS_PHP_VERSION < '5.5' ]; then echo 'extension=apc.so\n' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi"
 
services:
  - memcache
  - mongodb
  - redis-server

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm
  
after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
